[package]
name = "pesca-lang"
version = "0.1.0"
edition = "2021"
authors = ["Louis Meyer (H1ghBre4k3r) <h1ghbe4k3r@dev.bre4k3r.de>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/H1ghBre4k3r/pesca-parser"

[workspace]
members = ["crates/why_lib", "crates/lex_derive"]

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.15", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.124"
tokio = { version = "1.39.2", features = ["full"] }
tower-lsp = "0.20.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
why_lib = { path = "./crates/why_lib" }
