[package]
name = "pesca-lang"
version = "0.1.0"
edition = "2021"
authors = ["Louis Meyer (H1ghBre4k3r) <h1ghbe4k3r@dev.bre4k3r.de>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/H1ghBre4k3r/pesca-parser"

[workspace]
members = ["crates/why_lib", "crates/lex_derive"]

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.4.7", features = ["derive"] }
why_lib = { path = "./crates/why_lib" }
